config/routes.rb
Rails.application.routes.draw do
  resources :cryptos
  devise_for :users
  get 'subhome/about'
  get 'subhome/readme'
  get 'home/index'
  get 'home/about'
  get 'home/lookup'
  get 'home/table'
  get 'home/readme'
  post '/home/lookup' => 'home/lookup'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/crypto.rb
class Crypto < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :cryptos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: %i[ edit update destroy show ]
  # GET /cryptos or /cryptos.json
  def index
    @cryptos = Crypto.all
    require 'net/http'
    require 'json'
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=fd04676f-2762-4500-9f39-c0290aa0c3c8&start=1&limit=100&convert=USD'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_crypto = JSON.parse(@response)
    
  end

  # GET /cryptos/1 or /cryptos/1.json
  def show
    @cryptos = Crypto.all
    require 'net/http'
    require 'json'
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=fd04676f-2762-4500-9f39-c0290aa0c3c8&start=1&limit=100&convert=USD'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_crypto = JSON.parse(@response)
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit
  end

  # POST /cryptos or /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to crypto_url(@crypto), notice: "Crypto was successfully created." }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1 or /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to crypto_url(@crypto), notice: "Crypto was successfully updated." }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1 or /cryptos/1.json
  def destroy
    @crypto.destroy

    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: "Crypto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crypto_params
      params.require(:crypto).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end
    def correct_user
      @correct = current_user.cryptos.find_by(id: params[:id])
      redirect_to cryptos_path, notice: "Not Authorized to edit this entry" if @correct.nil?
      
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index #show infor 5 coins
    require 'net/http'
    require 'json'
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=fd04676f-2762-4500-9f39-c0290aa0c3c8&start=1&limit=100&convert=USD'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @coins = JSON.parse(@response)
    @my_coins = ["BTC","ETH","USDT","BNB","ADA"]
  end


  def lookup #search by symbol
    require 'net/http'
    require 'json'
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=fd04676f-2762-4500-9f39-c0290aa0c3c8&start=1&limit=100&convert=USD'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_coin = JSON.parse(@response)
    @input = params[:name_or_sym]
    @error = "Not found coin"
    @a = 0
    if @input 
      @input = @input.downcase
    end
  end
  def table #show table 100 rows
    require 'net/http'
    require 'json'
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=fd04676f-2762-4500-9f39-c0290aa0c3c8&start=1&limit=100&convert=USD'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @coins = JSON.parse(@response)
    @my_coins = ["BTC","ETH","USDT","BNB","ADA"]
  end
end

app/controllers/subhome_controller.rb
class SubhomeController < ApplicationController
  def about
  end

  def readme
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subhome_helper.rb
module SubhomeHelper
end

app/views/cryptos/_crypto.html.erb
<div id="<%= dom_id crypto %>">
<table class="table table-bordered", style="width:50%">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Symbol</th>
      <th scope="col">Cost_per</th>
      <th scope="col">Amount_owned</th>
    </tr>
  </thead>
  <tbody>
            <tr>
            <% for x in @lookup_crypto['data'] %>
            <% if crypto.symbol.upcase == x['symbol'] %> 
                    <td><%=  x['name'] %></td> 
                    <td><%= crypto.symbol.upcase %></td>
                    <td><%= crypto.cost_per %></td>
                    <td><%= crypto.amount_owned%></td>
                    <% end %> 
                    <% end %> 
            </tr>
  </tbody>
</table>
</div>

app/views/cryptos/_form.html.erb
<%= form_with(model: crypto) do |form| %>
  <% if crypto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

      <ul>
        <% crypto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :symbol, style: "display: block" %>
    <%= form.text_field :symbol %>
  </div>

  <div>
    <%= form.number_field :user_id, value: current_user.id, type: "hidden" %>
  </div>

  <div>
    <%= form.label :cost_per, style: "display: block" %>
    <%= form.text_field :cost_per %>
  </div>

  <div>
    <%= form.label :amount_owned, style: "display: block" %>
    <%= form.text_field :amount_owned %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cryptos/edit.html.erb
<h1>Editing crypto</h1>

<%= render "form", crypto: @crypto %>

<br>

<div>
  <%= link_to "Show this crypto", @crypto %> |
  <%= link_to "Back to cryptos", cryptos_path %>
</div>

app/views/cryptos/index.html.erb
<% profit_loss = 0%>
<h1>Portfolio</h1>
<br/>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Current Price</th>   
      <th>Current Value</th>
      <th>Total Paid</th> 
      <th>Profit/Loss</th>  
      <th>Cost Paid Per</th>
      <th>Amount owned</th>                    
    </tr>
  </thead>
  <tbody>
    <% @cryptos.each do |crypto|%>
      <%if crypto.user_id == current_user.id%>
        <% if crypto.symbol %>
          <% crypto.symbol = crypto.symbol.upcase%>
        <% end %>
        <tr>
        <% for x in @lookup_crypto['data'] %>
         <% if crypto.symbol == x['symbol'] %>  <%# search coin trong mang my_coins%>
             <td><%= link_to x['name'], crypto %></td> 
             <td><%= number_to_currency(x['quote']['USD']['price'])%></td>
             <td>$<%= (x['quote']['USD']['price'].to_d * crypto.amount_owned).round(4) %></td>
             <td>$<%= crypto.cost_per * crypto.amount_owned%></td>  
             <td>$<%= (x['quote']['USD']['price'].to_d * crypto.amount_owned) - (crypto.cost_per * crypto.amount_owned)%></td>
             <% profit_loss += (x['quote']['USD']['price'].to_d * crypto.amount_owned) - (crypto.cost_per * crypto.amount_owned)%>   
         <% end %> 
    <% end %>   
        <td>$<%= crypto.cost_per%></td>
        <td><%= crypto.amount_owned%></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<br/><div>
<strong>Portfolio Profit/Lost: </strong><%= number_to_currency(profit_loss)%>
</div>
<br/><br/>
<div>
<%= button_to 'New Crypto', new_crypto_path, method: :get, class: "btn btn-success"%>
</div>

app/views/cryptos/new.html.erb
<h1>New crypto</h1>

<%= render "form", crypto: @crypto %>

<br>

<div>
  <%= link_to "Back to cryptos", cryptos_path %>
</div>

app/views/cryptos/show.html.erb
<%= render @crypto %>
<div class="row justify-content-md-center">

<div class="col-2">
  <%= button_to "Edit this crypto", edit_crypto_path(@crypto), method: :get, class: "btn btn-success col" %> 
</div>

<div class="col-2">
  <%= button_to "Delete this crypto", @crypto, method: :delete, data: {confirm: "Are u sure?"}, class: "btn btn-danger col" %>
</div>

<div class="col-2">
  <%= link_to "Back to portfolio", cryptos_path,class: "btn btn-primary col" %>
</div>


</div>

app/views/header_footer/_flash.html.erb
<%flash.each do |name, msg|%>
    <div class="alert alert-danger alert-dismissible">
        <button class="close" data-dismiss="alert">
            <i class="glyphicon glyphicon-remove-circle"></i>
        </button>
        <%= content_tag(:div,msg)%>
    </div>
<% end %>

app/views/header_footer/_footer.html.erb
<!-- Footer -->
<footer class="mt-auto bg-dark text-white pt-4 pb-4">

  <!-- Footer Links -->
  <div class="container-fluid text-start text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-5 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase text-center fs-1">Rails Crypto</h5>
        <%# <p class="text-center"> organize your footer content.</p> %>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">
      <!-- Grid column -->
      <div class="col-md-2 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">company</h5>

        <ul class="list-unstyled">
          <li>
            <%= link_to "About Us", subhome_about_path, class:"text-decoration-none" %>
          </li>
          <li>
            <a href="#!" class="text-decoration-none">Term of use</a>
          </li>
          <%# <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li> %>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">support</h5>

        <ul class="list-unstyled">
          <li>
            <a href="readme" class="text-decoration-none">FAQ</a>
          </li>
          <li>
            <a href="#!" class="text-decoration-none" target="_blank">Request form</a>
          </li>
          <%# <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li> %>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Social</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!" class="text-decoration-none" target="_blank">Facebook</a>
          </li>
          <li>
            <a href="#!" class="text-decoration-none" target="_blank">Twitter</a>
          </li>
          <li>
            <a href="https://github.com/NguyenTungSon0503/RailsCrypto" class="text-decoration-none" target="_blank">Git Hub</a>
          </li>
          <%# <li>
            <a href="#!">Link 4</a>
          </li> %>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <br/>

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2022
    <a> RailsCrypto. All rights reserved</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/header_footer/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <%= link_to 'RailsCrypto', root_path, class:"navbar-brand align-top"%>
    <%# <a class="navbar-brand" href="#">RailsCrypto</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Search", home_lookup_path, class: "nav-link active"%>
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
        </li>
        
        <li class="nav-item">
            <%= link_to "Table", home_table_path, class: "nav-link active"%>
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
        </li>


        
        <% if user_signed_in? %>
          <%# <li class="nav-item">
            <%= link_to "Add New", new_crypto_path, class: "nav-link active"%>
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
       <%#</li>%> 

          <li class="nav-item">
            <%= link_to "Portfolio", cryptos_path, class: "nav-link active"%>
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
        </li>
            <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete,class: "nav-link active"%>
        </li>
        <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path,class: "nav-link active"%>
        </li>
        <% else %>
        <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link active"%>

            <%# <%= link_to "About Us", home_about_path, class:"nav-link" %>
          <%# <a class="nav-link" href="#">Link</a> %>
        </li>
        <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "nav-link active"%>
        </li>
          <% end %>>
        <%# <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li> %>
        <%# <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li> %>
      </ul>



      <%# <% search_bar %>
      <%# <form class="d-flex,">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary" type="submit">Search</button>
      </form> %>
              <%= form_tag home_lookup_path, :method => 'GET' do %>
              <%= text_field_tag 'name_or_sym', nil, placeholder:'Enter Crypto input', size: 20 %>
              <%= submit_tag 'Search'%>
              <%end%>

        
      
    </div>
  </div>
</nav>

app/views/home/lookup.html.erb
<h2>Look Up a single Coin Currency</h2>
<br/>
<%= form_tag home_lookup_path, :method => 'GET' do %>
 <%= text_field_tag 'name_or_sym', nil, placeholder:'Enter Crypto input', size: 30 %>
 <%= submit_tag 'Lookup Stock Quote'%>
 <%end%>
<br/>
<%if @input %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Symbol</th>
      <th scope="col">Price</th>
      <th scope="col">Volume</th>
    </tr>
  </thead>
  <tbody> 
  <%# search by symbol%>
    <% for x in @lookup_coin['data'] %>
        <% if x['name'].downcase.include?(@input) %>
           <tr>
                <td><%= x['cmc_rank']%></td>
                <td><%= x['name'] %></td>
                <td><%= x['symbol'] %></td>
                <td>$<%= x['quote']['USD']['price'].round(2)%></td>
                <td><%= x['quote']['USD']['volume_24h'].round(0)%></td>
            </tr>   
        <% elsif x['symbol'].downcase.include?(@input)  %>
        <tr>
                <td><%= x['cmc_rank']%></td>
                <td><%= x['name'] %></td>
                <td><%= x['symbol'] %></td>
                <td>$<%= x['quote']['USD']['price'].round(2)%></td>
                <td><%= x['quote']['USD']['volume_24h'].round(0)%></td>
            </tr>  
        <% elsif @input == ""%>
        <%="Not enter the field"%>
            <%break%>
          <%end%>        
    <% end %>     
     </tbody>
</table>
<% end %> 


app/views/home/readme.html.erb
# README

This README would normally document whatever steps are necessary to get the
application up and running.

Things you may want to cover:

* Ruby version

* System dependencies

* Configuration

* Database creation

* Database initialization

* How to run the test suite

* Services (job queues, cache servers, search engines, etc.)

* Deployment instructions

* ...

app/views/home/table.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Symbol</th>
      <th scope="col">Price</th>
      <th scope="col">Volume</th>
    </tr>
  </thead>
  <tbody>
    <% for x in @coins['data'] %>
        <%# <% for coin in @my_coins %> <%# gioi han coin trong mang my_coins%> 
            <%# <% if coin == x['symbol'] %>  <%# search coin trong mang my_coins%>
            <tr>
                    <td><%= x['cmc_rank']%></td>
                    <td><%= x['name'] %></td>
                    <td><%= x['symbol'] %></td>
                    <td>$<%= x['quote']['USD']['price'].round(2)%></td>  <%#number_to_currency(x['quote']['USD']['price'])%>
                    <td>$<%= x['quote']['USD']['volume_24h'].round(0)%></td>
            </tr>
            <%# <% end %>  
        <%# <% end %>  
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrypto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body class="d-flex flex-column min-vh-100">
  <%= render 'header_footer/header'%>  
  <%= render 'header_footer/flash'%>

  <%= yield %>
  <%= render 'header_footer/footer'%>

  </body>
</html>

app/views/subhome/about.html.erb
<h1>About Us</h1>
<p>My name is Son Nguyen</p>
<br/><br/>
array["rank"]

app/views/subhome/readme.html.erb
# README

This README would normally document whatever steps are necessary to get the
application up and running.

Things you may want to cover:

* Ruby version

* System dependencies

* Configuration

* Database creation

* Database initialization

* How to run the test suite

* Services (job queues, cache servers, search engines, etc.)

* Deployment instructions

* ...